#!/usr/bin/env bash
# Regenerates .claude/annotations/MANIFEST.md from all annotation files.
# Run after adding, removing, or renaming annotation files.
REPO=$(git rev-parse --show-toplevel)
ANNOTATIONS="$REPO/.claude/annotations"
MANIFEST="$ANNOTATIONS/MANIFEST.md"

{
    echo "# Annotation Manifest"
    echo ""
    echo "> Auto-generated by \`gen-annotations-manifest.sh\` — do not hand-edit."
    echo "> Annotations are injected by the PreToolUse hook when an agent touches the annotated file."
    echo ""
    echo "## Exact-Path Annotations"
    echo ""
    while IFS= read -r ann; do
        relative="${ann#$ANNOTATIONS/}"
        source="${relative%.md}"
        first_line=$(grep -v '^---' "$ann" | grep -v '^$' | grep -v '^severity:' | grep -v '^tags:' | head -1)
        echo "- \`$source\` — $first_line"
    done < <(find "$ANNOTATIONS" -name "*.md" ! -name "MANIFEST.md" ! -name "_patterns.yaml" | sort)
    echo ""
    echo "## Cross-Cutting Patterns (\`_patterns.yaml\`)"
    echo ""
    if [[ -f "$ANNOTATIONS/_patterns.yaml" ]]; then
        while IFS= read -r line; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            echo "- \`$line\`"
        done < "$ANNOTATIONS/_patterns.yaml"
    fi
} > "$MANIFEST"

echo "MANIFEST.md regenerated at $MANIFEST"
